### ISSUE TITLE
commitMutation does not work

### ISSUE THREAD

**Issue by HsuTing** [robrichard/relay-query-lookup-renderer#8]
This can not work when I use `commitMutation`.
I found the data was changed in relay store, but this did not get the change data.
I think the problem is `componentWillReceiveProps` in `relay-query-lookup-renderer`. For `commitMutation`, `query`, `environment`, `variables` dose not change. As a result, the result of this check is always `false`. This will not update a new store to `readyState`.
https://github.com/robrichard/relay-query-lookup-renderer/blob/master/src/index.js#L77-L81

Maybe we need to check the `readyState` in `relay-query-lookup-renderer` should be equal to the data in relay store?

Finally, thank you for doing this project. This is the best way for modern relay SSR I found.

**Comment by robrichard** [comment]
If the data in the store changes I think the subscription should call the `_onChange` method here: https://github.com/robrichard/relay-query-lookup-renderer/blob/master/src/index.js#L209

Does this issue also happen with the QueryRenderer included in `react-relay`?

It's also possible there are bugs here that have been fixed in the included QueryRenderer since this was copied and edited some time ago. I'm going to work on cutting a new release that updates with the latest from react-relay@1.4.0 soon

**Comment by HsuTing** [comment]
This issue does not happen with the QueryRenderer.
I am sure that it will return the same data after using `commitMutation`.
However, why you does not use `extends QueryRenderer` to build `relay-query-lookup-renderer`? This will be more easier than copy `QueryRenderer`.

**Comment by robrichard** [comment]
@HsuTing I'm concerned about that approach being even harder to maintain. A slight change in the way QueryRenderer is built in relay could break the extended component since the class structure is not part of the public API

**Comment by robrichard** [comment]
@HsuTing Please try the latest version [2.0.1](https://github.com/robrichard/relay-query-lookup-renderer/releases/tag/v2.0.1) and let me know if you still have this issue.

**Comment by omrihq** [comment]
I am still getting this issue. We have been calling window.location.reload after `commitMutation` because RQLR doesn't recognize the store changing. Any updates on this?

**Comment by robrichard** [comment]
@omrihq can you post a minimal reproduction? Can you also confirm this issue doesn't occur with the standard QueryRenderer included with Relay?

**Comment by omrihq** [comment]
@robrichard I ended up adding 
```
                 // data is available in the store, render without making any requests
                 const snapshot = environment.lookup(operation.fragment);
+                this._rootSubscription = environment.subscribe(snapshot, this._onChange);
```
in `_fetchForProps`, to avoid a stagnant cache in a local QRLR build. Can open up the PR if this is indeed a reasonable fix

**Comment by robrichard** [comment]
@omrihq sounds good, can you open a PR?

**Comment by omrihq** [comment]
@robrichard  https://github.com/robrichard/relay-query-lookup-renderer/pull/14

**Comment by robrichard** [comment]
Merged #14 and published v2.0.4
